version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 # Adjust the Python version as needed
    commands:
      - echo Installing dependencies
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo Running tests
      - make test